'use strict';
const express=require('express'),path=require('path'),fs=require('fs'),crypto=require('crypto'),multer=require('multer');
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);
const root=process.env.DATA_DIR||path.join(__dirname,'private-data');const pdfDir=path.join(root,'ebooks'),proofDir=path.join(root,'proofs');
for(const p of [root,pdfDir,proofDir])fs.mkdirSync(p,{recursive:true});
const dbPath=path.join(root,'orders.json');if(!fs.existsSync(dbPath))fs.writeFileSync(dbPath,'[]');
const read=()=>JSON.parse(fs.readFileSync(dbPath,'utf8'));
function write(orders){const temp=dbPath+'.tmp';fs.writeFileSync(temp,JSON.stringify(orders,null,2),{mode:0o600});fs.renameSync(temp,dbPath)}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024}});
app.use(express.json({limit:'20kb'}));app.use(express.urlencoded({extended:false}));
app.use(express.static(path.join(__dirname,'public'),{extensions:['html'],index:'index.html'}));
app.get('/health',(_,res)=>res.json({status:'ok'}));
const hits=new Map();function limit(req,res,next){const ip=req.ip,now=Date.now(),v=hits.get(ip)||[];const recent=v.filter(x=>now-x<3600000);if(recent.length>=12)return res.status(429).json({error:'Too many submissions. Try later.'});recent.push(now);hits.set(ip,recent);next()}
function admin(req,res,next){const configured=process.env.ADMIN_PASSWORD;if(!configured||configured.length<12)return res.status(503).send('Set ADMIN_PASSWORD (12+ characters) in Railway first.');const auth=req.headers.authorization||'';let pass='';try{if(auth.startsWith('Basic '))pass=Buffer.from(auth.slice(6),'base64').toString().split(':').slice(1).join(':')}catch{};const a=Buffer.from(pass),b=Buffer.from(configured);if(a.length!==b.length||!crypto.timingSafeEqual(a,b)){res.set('WWW-Authenticate','Basic realm="Course Admin"');return res.status(401).send('Admin authentication required')}next()}
app.post('/api/orders',limit,upload.single('proof'),(req,res)=>{try{const {name,phone,transaction}=req.body;const clean=x=>String(x||'').trim();if(!clean(name)||clean(name).length>80||!/^[+\d\s-]{8,20}$/.test(clean(phone))||clean(transaction).length<4||clean(transaction).length>100)return res.status(400).json({error:'Please enter valid name, phone and transaction ID.'});if(req.file&&!['image/png','image/jpeg','image/webp'].includes(req.file.mimetype))return res.status(400).json({error:'Screenshot must be PNG, JPG or WebP.'});const id=crypto.randomUUID();if(req.file)fs.writeFileSync(path.join(proofDir,id),req.file.buffer,{mode:0o600});const orders=read();orders.push({id,name:clean(name),phone:clean(phone),transaction:clean(transaction),proof:!!req.file,status:'pending',createdAt:new Date().toISOString(),token:null});write(orders);res.status(201).json({id,message:'Request received. Payment will be checked manually.'})}catch(e){console.error(e);res.status(500).json({error:'Submission failed. Please try again.'})}});
app.get('/admin',admin,(req,res)=>res.sendFile(path.join(__dirname,'admin.html')));
app.get('/api/admin/orders',admin,(req,res)=>res.json(read().map(({token,...o})=>({...o,hasAccess:!!token}))));
app.get('/api/admin/proof/:id',admin,(req,res)=>{const f=path.join(proofDir,path.basename(req.params.id));if(!fs.existsSync(f))return res.sendStatus(404);res.type('image/jpeg').sendFile(f)});
app.post('/api/admin/ebooks/:part',admin,upload.single('ebook'),(req,res)=>{const n=Number(req.params.part);if(!Number.isInteger(n)||n<1||n>5||!req.file||req.file.mimetype!=='application/pdf'||req.file.buffer.subarray(0,5).toString()!=='%PDF-')return res.status(400).json({error:'Upload a PDF for Part 1–5 (max 8MB).'});fs.writeFileSync(path.join(pdfDir,`part${n}.pdf`),req.file.buffer,{mode:0o600});res.json({ok:true})});
app.get('/api/admin/ebooks',admin,(_,res)=>res.json([1,2,3,4,5].map(n=>({part:n,uploaded:fs.existsSync(path.join(pdfDir,`part${n}.pdf`))}))));
app.post('/api/admin/approve/:id',admin,(req,res)=>{if(![1,2,3,4,5].every(n=>fs.existsSync(path.join(pdfDir,`part${n}.pdf`))))return res.status(409).json({error:'Upload all five PDFs before approving orders.'});const orders=read(),o=orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);o.status='approved';o.token=o.token||crypto.randomBytes(32).toString('hex');o.approvedAt=new Date().toISOString();write(orders);const origin=process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`;res.json({url:`${origin}/access/${o.token}`,phone:o.phone})});
app.get('/access/:token',(req,res)=>{const o=read().find(x=>x.token===req.params.token&&x.status==='approved');if(!o)return res.status(404).send('Invalid access link');res.type('html').send(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Your 5 English Course Books</title><style>body{font:18px system-ui;max-width:600px;margin:40px auto;padding:20px;color:#0b3056}a{display:block;padding:18px;margin:12px 0;background:#135187;color:white;border-radius:12px;text-decoration:none}</style></head><body><h1>🎉 Your English Speaking Course</h1><p>Payment verified. Download all five PDFs below. Keep this private link safe.</p>${[1,2,3,4,5].map(n=>`<a href="/download/${o.token}/${n}">📘 Download Part ${n}</a>`).join('')}</body></html>`)});
app.get('/download/:token/:part',(req,res)=>{const o=read().find(x=>x.token===req.params.token&&x.status==='approved'),n=Number(req.params.part);if(!o||!Number.isInteger(n)||n<1||n>5)return res.sendStatus(404);const f=path.join(pdfDir,`part${n}.pdf`);if(!fs.existsSync(f))return res.sendStatus(404);res.download(f,`English-Speaking-Course-Part-${n}.pdf`)});
app.use((err,req,res,next)=>{if(err.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'File exceeds 8 MB.'});console.error(err);res.status(500).json({error:'Unexpected error.'})});
app.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Course website running'));
